### ISSUE TITLE
ISSUE: No instructions in how AMAZON works

### ISSUE THREAD

**Issue by G3GhostTech** [moralmunky/Home-Assistant-Mail-And-Packages#103]
Can we get info in how amazon delivery will work?
ALSO,  will it read a FWD email? As I will not give any plugin to my main email account.

**Comment by moralmunky** [comment]
Amazon in early stages and may not be developed further which is why it is not documented. It’s a sensor and tracking list is put into the sensors attributes. 

You can have your delivery messages sent to a separate email address and use that to provide the integration or customize the code to fit your need. You would need to make changes in the const.py. You will need to be careful not to overwrite your changes when you upgrade and be aware of any changes that may break your customizations.
