### ISSUE TITLE
[Feature Request] Add Amazon UK tracking (and other countries?) 

### ISSUE THREAD

**Issue by tomanderson2** [moralmunky/Home-Assistant-Mail-And-Packages#125]
I noticed the addition of amazon canada emails and it would be great to include other countries as well? From the looks of things the only thing that really changes is the domain name, at least between US, Canada and UK.

Email from: shipment-tracking@amazon.co.uk

Screenshots show the details which seem the same looking through the code? Maybe dates are different format? 

![amazon](https://user-images.githubusercontent.com/3867456/82062537-2cf07780-96c2-11ea-9c29-e633f699241b.png)
![amazon-dispatched](https://user-images.githubusercontent.com/3867456/82062548-3083fe80-96c2-11ea-8a46-cf76dbbad250.png)

If you need any other details or someone to test I'm happy to help where I can

**Comment by firstof9** [comment]
I'll see about adding it, in the meantime you could change it to ```amazon.co.uk``` in the ```const.py``` file.

**Comment by firstof9** [comment]
I've added this to ```0.2.1-b1``` for ```.ca``` and ```.co.uk```

**Comment by firstof9** [comment]
This [sensor.py](https://raw.githubusercontent.com/firstof9/Home-Assistant-Mail-And-Packages/0.2.x/custom_components/mail_and_packages/sensor.py) should catch those international emails now. Let me know how it goes @calvinwankhede

**Comment by calvinwankhede** [comment]
Thanks, I've installed -b5. Will update when I get a chance to test it out.

**Comment by calvinwankhede** [comment]
Alright, I ordered something off Amazon to test this out and while the detection works fine, there's still some issues that need to be ironed out. I'm creating a PR to fix the simple ones.

Additionally, I had the same problem as #141 - no TypeError because of quopri, but got the same debug line:
`2020-06-14 21:56:39 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Error attempting prase Amazon email: 'utf-8' codec can't decode byte 0xda in position 7782: invalid continuation byte`

In my case anyway, this error was caused by the following email:

**Comment by calvinwankhede** [comment]
Alright, I ordered something off Amazon to test this out and while the detection works fine, there's still a few issues that need to be ironed out. I'll create a PR soon.

Additionally, I had the same problem as #141 - no TypeError because of quopri, but got the same debug line:
`2020-06-14 21:56:39 DEBUG (MainThread) [custom_components.mail_and_packages.sensor] Error attempting prase Amazon email: 'utf-8' codec can't decode byte 0xda in position 7782: invalid continuation byte`

In my case, this error was caused by the following email, which is text/html only:
![image](https://user-images.githubusercontent.com/25424553/84598945-0160d880-ae8c-11ea-9427-7b3f172f1772.png)

I believe that these transactional emails shouldn't be read in the first place since Amazon Pay can also be a payment gateway for third-party websites here in India.

I propose filtering emails so that only this format `shipment-tracking@ Amazon domains` is picked up. Based on OP's screenshot, UK and IN regions use the same format. Not sure about US/CAN.

**Comment by moralmunky** [comment]
order-update@amazon.com provides the amazon internal contract shippers delivery notifications.

**Comment by firstof9** [comment]
For my shipping notices then come like so:

From: shipment-tracking@amazon.com
Subject line: Your Amazon.com order #XXX-XXXXXXX-XXXXXXX has shipped

Does the subject line for your Amazon.in emails look like this as well, except with Amazon.in?

**Comment by calvinwankhede** [comment]
Here's the from and subject lines:

![Screenshot from 2020-06-15 16-29-28](https://user-images.githubusercontent.com/25424553/84651923-5a7e4a00-af28-11ea-8df0-e4518313e5f5.jpg)

**Comment by firstof9** [comment]
Ok perfect, this gives me an idea.

**Comment by firstof9** [comment]
@calvinwankhede 0.2.1-b6 has your adjustments and my subject line tweak in it. Should go well together.

**Comment by calvinwankhede** [comment]
Updated, regex approach looks clean.

**Comment by firstof9** [comment]
Now that there's a const setup for the Amazon domain names we can basically support any country Amazon operates in when requested.
