### ISSUE TITLE
ISSUE: Incorrect sensor.mail_packages_in_transit count

### ISSUE THREAD

**Issue by rpitera** [moralmunky/Home-Assistant-Mail-And-Packages#583]
**Describe the bug**
Getting proper values for UPS and Amazon sensors; in the example one package each. But sensor.mail_packages_in_transit count shows a value of one, instead of two as expected (unless I've misunderstood the intent of this sensor).

**Environment (please complete the following information):**
 - OS: HassOS
 - Type of device: Dedicated Virtualbox VM server
 - Home Assistant version: 2021.11.5
 - Hassio
 - Component version: 0.3.3-2

**Logs**
Nothing in HA Logs; will run debug on request.

**Screenshots**

![Clipboard01](https://user-images.githubusercontent.com/19910294/143269607-a21e6803-8844-4108-88fc-b4c2de8d6384.png)

![Clipboard02](https://user-images.githubusercontent.com/19910294/143269629-ab06c2e2-0ac4-4d1b-813a-da1201686123.png)

**Comment by rpitera** [comment]
Additional context: Just wanted to verify that the Amazon delivery is coming via Amazon, not a handoff to USPS or anything.

**Comment by firstof9** [comment]
Amazon sensors are not included in the "in transit" count. We [cover that in the wiki](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/wiki#amazon) at the very bottom.

Mainly due to the fact that they don't _always_ ship via their own carrier, we don't add them to the total to try and keep the count accurate as possible.

**Comment by rpitera** [comment]
Thanks for the explanation Chris - I looked through the Wiki too fast and missed that (despite the **bold face** - duh!) so I appreciate it.
