### ISSUE TITLE
Install Imagemagick

### ISSUE THREAD

**Issue by gdreelin** [moralmunky/Home-Assistant-Mail-And-Packages#6]
How would I go about installing the imagemagick  on Proxmox container version of HASSIO? I tried from the HASSIO command line but very limited commands can be run once you login into it.

**Comment by moralmunky** [comment]
Answered in forum. Adding answer for reference.

HASS.io doe not allow access to add additional linux packages. I think the solution would be creating a community add-on that installs Imagemagick.

You need to install imagmagick inside the VM. I also use PROXMOX and have it manually installed HASS in a CT (LXC container) instead of a VM, less overhead than the VM in PROXMOX. I used the ‘Alternative Installs’ as a guide.

You do lose access to the add-on library that is part of Hass.io.
