### ISSUE TITLE
UPS Mail Different

### ISSUE THREAD

**Issue by gdreelin** [moralmunky/Home-Assistant-Mail-And-Packages#7]
On the current settings it has mcinfo@ups.com and from the US UPS it comes in via pkginfo@ups.com. May want an "OR" statement to use both of them? Don't really know but I figured I would bring it up.

**Comment by moralmunky** [comment]
Answered in forum, adding for reference.

It appears you are subscribed to a UPS service called Quantum View which is meant for businesses with complex tracking needs. Consumers subscribe to UPS MyChoice. This is what our email logic is based on.

In order to support Quantum we would need all possible subject lines that are sent for shipment status changes. I will add some notes in the development project, I don’t have immediate plans to implement. There are other details that would need to be hashed out and implemented in order to add this method and them majority of users are most likely using the consumer tool from UPS.
