### ISSUE TITLE
[Feature Request] Allow self signed certificates

### ISSUE THREAD

**Issue by NotExpectedYet** [moralmunky/Home-Assistant-Mail-And-Packages#805]
**Is your feature request related to a problem? Please describe.**
I can't connect to my local proton mail instance without allowing self signed certificates as the protonmail bridge wraps all connections in them. 

**Describe the solution you'd like**
A little tick box in the UI would be nice to ignore/accept self signed certificates

**Describe alternatives you've considered**
Not entirely sure what I could do to work around this in this configuration

**Additional context**
I'm using a local installation of Proton Mail - Bridge. This is running on docker with ports 25 and 143 exposed externally.

**Comment by firstof9** [comment]
You'd need to load your CA cert into the HA container each update in order to get this to work.
This is out of the scope of the integration.

**Comment by AngellusMortis** [comment]
imap allows passing [SSL context](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4_SSL
), which can skip [cert validation](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname). You can add a checkbox to allow the user to not verify the SSL cert. This is _very_ common in HA integrations since it is very likely for people to use self-signed certs for various reasons locally.

This is the _only_ way to connect to Proton Mail via IMAP since [everything is E2E encrypted](https://proton.me/support/why-you-need-bridge). It is hard to find to market share numbers since providers do not regularly post how many users they have, but Proton Mail is likely the 4th or 5th largest email provider now. Either right behind or before Yahoo! mail, but still behind Gmail, Outlook and Apple. 

Supporting Proton is better than not supporting it. Unverified SSL checks are better than not support and/or not using SSL at all.
