### ISSUE TITLE
ISSUE: Event Looping Error after Home Assistant version 2024.6.x

### ISSUE THREAD

**Issue by clowncracker** [moralmunky/Home-Assistant-Mail-And-Packages#908]
**Describe the bug**
Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.p

**Environment (please complete the following information):**
 - OS: HAOS
 - Type of device: Unraid VM
 - Home Assistant version: 2024.6.1
 - Supervisor: 2024.06.0
 - Component version: 0.3.27

**Logs**
```Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 12:49:32 PM (98 occurrences)
Last logged: 9:43:01 PM

Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 1148: with open(filepath, "wb") as the_file: (offender: /config/custom_components/mail_and_packages/helpers.py, line 1148: with open(filepath, "wb") as the_file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/mail_and_packages/helpers.py", line 1148, in download_img with open(filepath, "wb") as the_file:```

**Comment by firstof9** [comment]
Thanks should be fix in the next release.

**Comment by clowncracker** [comment]
@firstof9 when is the next release going to be?  I'd love to get this cleared out of my logs.

**Comment by firstof9** [comment]
I was hoping to get one more PR in before release for a new feature, but looks like that one will have to wait.
I'll tag a release shortly.

**Comment by clowncracker** [comment]
After updating to 0.3.28, my VM literally won't even start now.

**Comment by firstof9** [comment]
what messages do you see in the console of the VM?

**Comment by clowncracker** [comment]
It seems to have resolved itself, I was able to update to 0.3.28.

I don't know if this has solved the looping issue though, since I've determined that this addon is the source of a ton of timeout errors I was having for other unrelated addons per https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/906.  I have this addon disabled until that ticket is resolved.

**Comment by lazyboy0172** [comment]
unfortunately I'm not much help aside from chiming in, but 0.3.28 also broke my HA instance. My server was unresponsive today and I could not figure out why-- couldn't login via web interface at all, nothing was working and I had no idea why. After rebooting the device a few times and my router once, I eventually physically connected the pi4 to a monitor and worked within the CLI to check logs. There were a handful of warnings (including mail_and_packages) but nothing that seemed critically bad, so at this point I feared hardware issues. In the meantime I restored from last night's backup and was up and running shortly after. I went through everything in my config and all seemed well, no smoking guns for the culprit. After an hour or so of everything running fine again and having checked my configuration I noticed Mail_and_packages had a pending update, 0.3.28, and I applied it. Restarted Home Assistant and again, it never came back up. Since this time it was immediately after I manually updated this component, instead of restoring a full snapshot I simply deleted the mail_and_packages folder in the custom_components via the CLI. rebooted and everything came back up and working, save for a warning/notification about could not start mail_and_packages (as expected). I re-downloaded 0.3.25 just to be safe, restarted HA again and everything actually booted back up. Like the poster above I decided to disable the addon until things seem resolved, I need system stability way more than pictures of my incoming mail.

Sorry to not be the most help since I don't have logs to provide, but I came here after getting everything working again to see if others experienced issues with 0.3.28 and found this post. Just wanted to put in my two cents and corroborate the above poster's issue

**Comment by clowncracker** [comment]
@lazyboy0172 I had to restore from a backup as well, the update literally bricked my VM.  There weren't any issues in the VM logs, the UI just wouldn't load.  There are definitely issues with the addon since the update to HA 2024.6.x and 0.3.26.  It's causing instability for a ton of other addons on top of other issues.

**Comment by LukeAbell** [comment]
Same thing happened to me. The Web UI broke right after configuring the addon. Had to SSH into the VM and remove the mail_and_packages folder.

**Comment by SeanPM5** [comment]
Also broke my system, but I suspect it's probably related to the SSL stuff in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/pull/913 and not this blocking call fix. After updating to  `0.3.28` my system took a long time to boot up and wasn't connecting to any http, wasn't able to access via companion app etc.  (the error in mobile app was -- "An SSL error has occurred and a secure connection to the server cannot be made.")

Restored and went back to `0.3.27` and it's working fine again.

Running HA OS & HA Cloud. Fairly standard/common setup, although I have IPv6 disabled under HA's network settings.

**Comment by firstof9** [comment]
Please try `0.3.29b0` and see if this resolves your issue.

**Comment by clowncracker** [comment]
@firstof9 system didn't crash, but I do see this in the logs now:

```
Logger: homeassistant.util.loop
Source: util/loop.py:84
First occurred: 5:09:22 PM (1 occurrences)
Last logged: 5:09:22 PM

Detected blocking call to open inside the event loop by custom integration 'mail_and_packages' at custom_components/mail_and_packages/helpers.py, line 1184: with open(filepath, "wb") as the_file: (offender: /config/custom_components/mail_and_packages/helpers.py, line 1184: with open(filepath, "wb") as the_file:), please create a bug report at https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/config/custom_components/mail_and_packages/helpers.py", line 1184, in download_img with open(filepath, "wb") as the_file:

I don't know if https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/906#issuecomment-2184243018 has resolved, need to leave the addon on for a few hours to see what happens.

**Comment by firstof9** [comment]
@clowncracker  `0.3.29b1` should take care of the io blocking you found.

**Comment by clowncracker** [comment]
@firstof9 no errors in the logs after restarting with 0.3.29b1.  I'll check back in a couple of hours and will let you know if I see anything in the logs.

**Comment by clowncracker** [comment]
@firstof9 I've not had any issues since upgrading to version `0.3.29b1`.
