### ISSUE TITLE
Feature Request: Add support for Proton Mail

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#912]
imaplib allows passing [SSL context](https://docs.python.org/3/library/imaplib.html#imaplib.IMAP4_SSL
), which can skip [cert validation](https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname). You can add a checkbox to allow the user to not verify the SSL cert. This is _very_ common in HA integrations since it is very likely for people to use self-signed certs for various reasons locally.

This is the _only_ way to connect to Proton Mail via IMAP since [everything is E2E encrypted](https://proton.me/support/why-you-need-bridge). It is hard to find to market share numbers since providers do not regularly post how many users they have, but Proton Mail is likely the 4th or 5th largest email provider now. Either right behind or before Yahoo! mail, but still behind Gmail, Outlook and Apple. 

Supporting Proton is better than not supporting it. Unverified SSL checks are better than not supporting and/or not using SSL at all.

_Originally posted by @AngellusMortis in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/issues/805#issuecomment-2178696536_

**Comment by AngellusMortis** [comment]
Tested the new option. It does not quite work. This is technically another feature request without this issue is worded, but if it is instead changed to "support Proton Mail" it is under the same issue.

The Proton Mail Bridge does not support IMAP over SSL. It only uses IMAP over STARTTLS. So instead of

```python
account = imaplib.IMAP4_SSL(host=host, port=port, ssl_context=context)
```

you need

```python
account = imaplib.IMAP4(host=host, port=port)
account.starttls(context)
```

This is what Paperless (another Python project that uses IMAP) uses: https://github.com/ikvk/imap_tools/blob/master/imap_tools/mailbox.py#L305-L364

This may be a good time to add a select drop down to choose between unencrypted, SSL and STARTTLS and then default it to SSL (existing behavior). That would allow it to support more options out of the box instead of implementing _just_ STARTTLS for Proton Mail Bridge.

(again from Paperless):

![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/490848/0b90bb0b-b749-4f74-9ffc-e9d0ed527c99)

**Comment by firstof9** [comment]
Thanks I'll take a look.

**Comment by firstof9** [comment]
![image](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/assets/1105672/ec23b60f-d9cb-4edf-b02c-b7a6a778d8b6)

This is how HA displays 3 options, rather than a drop down, it throws radio buttons.

**Comment by firstof9** [comment]
Please try `0.3.29b0` and see if this resolves your issue.

**Comment by AngellusMortis** [comment]
Config flow works, but the integration never initializes. Only thing in the HA logs is 

```
Timeout fetching Mail and Packages (192.168.2.203) data
```

Running code from helpers, `login`, `selectfolder`, `email_search` (for USPS emails) and `email_fetch` all work as expected. 

I can test anything specifically you want, or you can make a Proton Mail account as they are free. You will then need to set up Proton Mail Bridge though. There is a [docker container](https://github.com/shenxn/protonmail-bridge-docker) to do it. Just make sure you read the README since it requires manual setup.

**Comment by firstof9** [comment]
Looks like free accounts are unable to use the bridge.
Can you enable debug logs for the integration using the bridge?

**Comment by AngellusMortis** [comment]
It seemed like HA did not actually use the new version of Mail and Packages for some reason. Maybe the pyc cache did not get cleared right or something. After restarting again, it started working.

**Comment by AngellusMortis** [comment]
So yeah, everything seems to be working with Proton now.

1. Set up Proton Mail Bridge ([docker container](https://github.com/shenxn/protonmail-bridge-docker/issues)). If you are using the container, make sure you run the `info` command after initial set up to get the connection details for the bridge.
2. If you are not using the docker container, you probably need to forward the port for IMAP with socat since it is bound to `127.0.0.1` by mail bridge. 
3. Add Integration with credential details given by mail bridge. Should be using `startTLS` and No verification of SSL cert.  Username and password provided by mail bridge. 


Can you rename this issue to "Add support for Proton Mail" before you close it so others can find it better if they are looking?

**Comment by firstof9** [comment]
I've added those details to a Proton Mail section of the Wiki.
Thanks!
