### ISSUE TITLE
Bug: amazon.de - delivered - no count

### ISSUE THREAD

**Issue by firstof9** [moralmunky/Home-Assistant-Mail-And-Packages#995]
### Discussed in https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/discussions/994

<div type='discussions-op-text'>

<sup>Originally posted by **jeanjacquesjj** November 11, 2024</sup>
Hello,

I just started with Mail & Packages and saw that my Amazon "delivered" sensor is not increasing. In my case 2 Amazon packages delivered in Germany and 2 mails received today in German. 

I'm absolutely not capable of reading code, but I saw an issues in the log-file:
- the title of the delivery mail is "Zugestellt: deine Amazon.de-Bestellung", search pattern seems to be: SUBJECT "Geliefert:" SINCE 11-Nov-2024 ...
So it says: _Amazon delivered email(s) found: 0_

It added "Zugestellt:", in line 102 of const.py and the sensor wet to "2" - perfect !

Perhaps this helps, but once again, I'm far from being a developer !
Thank you so much for your work !
JJ
</div>

**Comment by firstof9** [comment]
Need to add `Zugestellt:` to the amazon delivered email subject search.

**Comment by jeanjacquesjj** [comment]
I just noticed, that there might be a confusion using "Zugestellt:" because a delivering mail is counted ("Zustellung heute: Ihr Amazon Paket wird zugestellt.").
Recap: The delivered subject is: "Zugestellt: deine Amazon.de-Bestellung mit Bestellnr.XXX", 
the delivering is "Zustellung heute: Ihr Amazon Paket wird zugestellt."

I might be better to add **Zugestellt: deine** to the subject search.

**Comment by firstof9** [comment]
[0.4.2-b4](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages/releases/tag/0.4.2-b4)

This should fix it up. Please let me know if it doesn't.

**Comment by BenGeba** [comment]
This fixed the Mail Amazon Packages Delivered sensor for me. Thank you
